import type { Locale } from './locale'

type Tri = { vi: string; ko: string }

// UI chrome strings (labels, CTAs, section headings) keyed by the English
// source. English is the key and the fallback, so any un-added string simply
// renders in English instead of breaking. Seed/CMS content uses `localize()`
// separately — this map is only for hardcoded interface copy.
const UI: Record<string, Tri> = {
  // ── Nav ──
  'About': { vi: 'Giới thiệu', ko: '소개' },
  'Events': { vi: 'Sự kiện', ko: '행사' },
  'News': { vi: 'Tin tức', ko: '뉴스' },
  'Membership': { vi: 'Hội viên', ko: '회원' },
  'Experts': { vi: 'Chuyên gia', ko: '전문가' },
  'Contact': { vi: 'Liên hệ', ko: '문의' },
  'Join KBIT': { vi: 'Tham gia KBIT', ko: 'KBIT 가입' },

  // ── Footer ──
  'Korean Beauty International Technology': { vi: 'Korean Beauty International Technology', ko: 'Korean Beauty International Technology' },
  'Clinical education, partnerships, and global exchange.': {
    vi: 'Đào tạo lâm sàng, hợp tác và giao lưu toàn cầu.',
    ko: '임상 교육, 파트너십, 글로벌 교류.',
  },
  'Contact KBIT': { vi: 'Liên hệ KBIT', ko: 'KBIT 문의하기' },
  'Offices': { vi: 'Văn phòng', ko: '사무소' },
  'Korean Beauty International Technology Association — advancing clinical excellence across Korea, Vietnam, and beyond.': {
    vi: 'Hiệp hội Công nghệ Thẩm mỹ Quốc tế Hàn Quốc — nâng tầm chất lượng lâm sàng tại Hàn Quốc, Việt Nam và hơn thế nữa.',
    ko: '한국뷰티국제기술협회 — 한국과 베트남을 비롯한 전역에서 임상 우수성을 발전시킵니다.',
  },
  'Explore': { vi: 'Khám phá', ko: '둘러보기' },
  'Association': { vi: 'Hiệp hội', ko: '협회' },
  'Partners': { vi: 'Đối tác', ko: '파트너' },
  'Centers': { vi: 'Trung tâm', ko: '센터' },
  'Office locations →': { vi: 'Địa chỉ văn phòng →', ko: '사무소 위치 →' },

  // ── NotFound ──
  'Page not found': { vi: 'Không tìm thấy trang', ko: '페이지를 찾을 수 없습니다' },
  '← Back to home': { vi: '← Về trang chủ', ko: '← 홈으로 돌아가기' },

  // ── Common CTAs / labels (shared across pages) ──
  'Learn More': { vi: 'Tìm hiểu thêm', ko: '더 알아보기' },
  'Upcoming Events': { vi: 'Sự kiện sắp tới', ko: '예정된 행사' },
  'Read story': { vi: 'Đọc bài', ko: '기사 읽기' },
  'Back to News': { vi: 'Quay lại Tin tức', ko: '뉴스로 돌아가기' },
  'Published': { vi: 'Ngày đăng', ko: '게시일' },
  'Reading time': { vi: 'Thời gian đọc', ko: '읽는 시간' },
  'Featured': { vi: 'Nổi bật', ko: '주요 기사' },
  'views': { vi: 'lượt xem', ko: '조회' },
  'Submit credentials': { vi: 'Gửi hồ sơ', ko: '자격 제출' },

  // ── Home ──
  'KBIT Association': { vi: 'Hiệp hội KBIT', ko: 'KBIT 협회' },
  'Clinical': { vi: 'Lâm sàng', ko: '임상' },
  'Exchange': { vi: 'Giao lưu', ko: '교류' },
  'Korea / Asia': { vi: 'Hàn Quốc / Châu Á', ko: '한국 / 아시아' },
  'Education Centers': { vi: 'Trung tâm đào tạo', ko: '교육 센터' },
  'Expert Doctors': { vi: 'Bác sĩ chuyên gia', ko: '전문 의료진' },
  'Doctors': { vi: 'Bác sĩ', ko: '의료진' },
  'Countries': { vi: 'Quốc gia', ko: '국가' },
  'Members': { vi: 'Hội viên', ko: '회원' },
  'About KBIT': { vi: 'Về KBIT', ko: 'KBIT 소개' },
  'Advancing Korean Beauty & Medical Technology': {
    vi: 'Phát triển công nghệ thẩm mỹ và y tế Hàn Quốc',
    ko: '한국 뷰티·의료 기술의 발전',
  },
  "KBIT connects Korea's foremost clinical experts with medical professionals and institutions across Asia and beyond. Through rigorous training, international events, and curated partnerships, we drive the future of aesthetic medicine.": {
    vi: 'KBIT kết nối các chuyên gia lâm sàng hàng đầu Hàn Quốc với các chuyên gia và tổ chức y tế trên khắp châu Á và hơn thế nữa. Thông qua đào tạo bài bản, các sự kiện quốc tế và mạng lưới đối tác chọn lọc, chúng tôi định hình tương lai của y học thẩm mỹ.',
    ko: 'KBIT는 한국 최고의 임상 전문가들을 아시아 전역과 그 너머의 의료 전문가 및 기관과 연결합니다. 엄격한 교육, 국제 행사, 엄선된 파트너십을 통해 미용의학의 미래를 이끕니다.',
  },
  'Events & Workshops': { vi: 'Sự kiện & Hội thảo', ko: '행사 및 워크숍' },
  'Upcoming Programs': { vi: 'Chương trình sắp tới', ko: '예정된 프로그램' },
  'View all events →': { vi: 'Xem tất cả sự kiện →', ko: '모든 행사 보기 →' },
  'Past': { vi: 'Đã diễn ra', ko: '종료' },
  'Upcoming': { vi: 'Sắp tới', ko: '예정' },
  'Scientific & Industry Partners': { vi: 'Đối tác Khoa học & Ngành', ko: '과학 및 산업 파트너' },
  'Ready to Elevate Your Practice?': {
    vi: 'Sẵn sàng nâng tầm phòng khám của bạn?',
    ko: '진료 수준을 높일 준비가 되셨나요?',
  },
  'Join the Vanguard of Korean Clinical Excellence': {
    vi: 'Gia nhập đội ngũ tiên phong về chất lượng lâm sàng Hàn Quốc',
    ko: '한국 임상 우수성의 선두에 합류하세요',
  },
  "Access world-class training, global networks, and Korea's most advanced aesthetic protocols.": {
    vi: 'Tiếp cận đào tạo đẳng cấp thế giới, mạng lưới toàn cầu và các phác đồ thẩm mỹ tiên tiến nhất của Hàn Quốc.',
    ko: '세계적 수준의 교육, 글로벌 네트워크, 그리고 한국의 가장 진보된 미용 프로토콜을 만나보세요.',
  },
  'Apply for Membership': { vi: 'Đăng ký Hội viên', ko: '회원 신청' },
  'Contact Us': { vi: 'Liên hệ với chúng tôi', ko: '문의하기' },

  // ── Events ──
  'Programs & Education': { vi: 'Chương trình & Đào tạo', ko: '프로그램 및 교육' },
  'Global Workshops & Clinical Summits': {
    vi: 'Hội thảo Toàn cầu & Hội nghị Lâm sàng',
    ko: '글로벌 워크숍 & 임상 서밋',
  },
  "Join Korea's leading clinicians at international events bridging evidence-based aesthetics and hands-on training.": {
    vi: 'Tham gia cùng các bác sĩ hàng đầu Hàn Quốc tại các sự kiện quốc tế kết nối thẩm mỹ dựa trên bằng chứng và đào tạo thực hành.',
    ko: '근거 기반 미용과 실습 교육을 잇는 국제 행사에서 한국 최고의 임상의들과 함께하세요.',
  },
  'All Events': { vi: 'Tất cả sự kiện', ko: '전체 행사' },
  'Past Events': { vi: 'Sự kiện đã qua', ko: '지난 행사' },
  'Featured Event': { vi: 'Sự kiện nổi bật', ko: '주요 행사' },
  'Past Event': { vi: 'Đã diễn ra', ko: '종료된 행사' },
  'View detail': { vi: 'Xem chi tiết', ko: '상세 보기' },
  'Request program info': { vi: 'Yêu cầu thông tin chương trình', ko: '프로그램 정보 요청' },
  'Program Index': { vi: 'Danh mục chương trình', ko: '프로그램 목록' },
  'Explore KBIT clinical programs': {
    vi: 'Khám phá các chương trình lâm sàng KBIT',
    ko: 'KBIT 임상 프로그램 둘러보기',
  },
  'Programs listed': { vi: 'Chương trình được liệt kê', ko: '등록된 프로그램' },
  'Upcoming programs': { vi: 'Chương trình sắp tới', ko: '예정 프로그램' },
  'Past programs': { vi: 'Chương trình đã qua', ko: '지난 프로그램' },
  'Multilingual': { vi: 'Đa ngôn ngữ', ko: '다국어' },
  'No upcoming events found.': { vi: 'Không tìm thấy sự kiện sắp tới.', ko: '예정된 행사가 없습니다.' },
  'No past events found.': { vi: 'Không tìm thấy sự kiện đã qua.', ko: '지난 행사가 없습니다.' },

  // ── News (list) ──
  'News / Stories / Archive': { vi: 'Tin tức / Câu chuyện / Lưu trữ', ko: '뉴스 / 스토리 / 아카이브' },
  'Spotlight index': { vi: 'Mục nổi bật', ko: '주요 기사 색인' },
  'Archive count': { vi: 'Số bài lưu trữ', ko: '아카이브 수' },
  'stories': { vi: 'bài viết', ko: '기사' },
  'more below': { vi: 'thêm bên dưới', ko: '아래 더보기' },
  'Latest archive': { vi: 'Lưu trữ mới nhất', ko: '최신 아카이브' },
  'More articles': { vi: 'Thêm bài viết', ko: '더 많은 기사' },

  // ── News detail ──
  'News not found': { vi: 'Không tìm thấy tin', ko: '뉴스를 찾을 수 없습니다' },
  'We could not find this story.': { vi: 'Chúng tôi không tìm thấy bài viết này.', ko: '해당 기사를 찾을 수 없습니다.' },
  'Loading story…': { vi: 'Đang tải bài viết…', ko: '기사 불러오는 중…' },
  'News story': { vi: 'Bài viết', ko: '뉴스 기사' },
  'KBIT NEWS ARCHIVE': { vi: 'KHO TIN KBIT', ko: 'KBIT 뉴스 아카이브' },
  'Story info': { vi: 'Thông tin bài', ko: '기사 정보' },
  'min': { vi: 'phút', ko: '분' },
  'Selected frames': { vi: 'Hình ảnh chọn lọc', ko: '선별 이미지' },
  'Related stories': { vi: 'Bài liên quan', ko: '관련 기사' },
  'Edition': { vi: 'Chuyên mục', ko: '에디션' },

  // ── Experts ──
  'Key Doctors & Specialists': { vi: 'Bác sĩ & Chuyên gia chủ chốt', ko: '핵심 의료진 및 전문가' },
  'Credentials and clinical scope are reviewed before a profile is published.': {
    vi: 'Bằng cấp và phạm vi lâm sàng được rà soát trước khi hồ sơ được công bố.',
    ko: '프로필 공개 전 자격과 진료 범위를 검토합니다.',
  },
  'Specialties, teaching roles, and regional availability are structured for browsing.': {
    vi: 'Chuyên khoa, vai trò giảng dạy và khu vực hoạt động được sắp xếp để dễ tra cứu.',
    ko: '전문 분야, 강의 역할, 지역별 활동을 보기 쉽게 정리합니다.',
  },
  'Verified doctors can be connected to events, training programs, and member benefits.': {
    vi: 'Bác sĩ đã xác minh có thể kết nối với sự kiện, chương trình đào tạo và quyền lợi hội viên.',
    ko: '인증된 의료진은 행사, 교육 프로그램, 회원 혜택과 연결될 수 있습니다.',
  },
  'Expert directory': { vi: 'Danh bạ chuyên gia', ko: '전문가 디렉터리' },
  'Verified clinical profiles': { vi: 'Hồ sơ lâm sàng đã xác minh', ko: '인증된 임상 프로필' },
  'Verified clinical profiles are being prepared': {
    vi: 'Hồ sơ lâm sàng đã xác minh đang được chuẩn bị',
    ko: '인증된 임상 프로필을 준비하고 있습니다',
  },
  'KBIT is organizing doctor profiles around credentials, specialty focus, training role, and international collaboration readiness. Until every profile is verified, the public page presents the qualification framework rather than placeholder biographies.': {
    vi: 'KBIT đang sắp xếp hồ sơ bác sĩ theo bằng cấp, lĩnh vực chuyên môn, vai trò đào tạo và mức độ sẵn sàng hợp tác quốc tế. Cho đến khi mọi hồ sơ được xác minh, trang công khai trình bày khung tiêu chuẩn thay vì các tiểu sử tạm.',
    ko: 'KBIT는 자격, 전문 분야, 교육 역할, 국제 협력 준비도를 기준으로 의료진 프로필을 정리하고 있습니다. 모든 프로필이 인증될 때까지 공개 페이지는 임시 약력 대신 자격 기준을 제시합니다.',
  },
  'Request expert connection': { vi: 'Yêu cầu kết nối chuyên gia', ko: '전문가 연결 요청' },
  'Collaborate with KBIT': { vi: 'Hợp tác với KBIT', ko: 'KBIT와 협력하기' },
  'Join our expert network': { vi: 'Tham gia mạng lưới chuyên gia', ko: '전문가 네트워크에 참여하세요' },

  // ── Centers ──
  'Content coming soon.': { vi: 'Nội dung sẽ sớm ra mắt.', ko: '콘텐츠가 곧 제공됩니다.' },
  'Center Network': { vi: 'Mạng lưới trung tâm', ko: '센터 네트워크' },
  'What to expect': { vi: 'Điều bạn nhận được', ko: '기대할 수 있는 것' },
  'Korean-standard excellence': { vi: 'Chất lượng chuẩn Hàn Quốc', ko: '한국 표준의 우수성' },
  'Education Center': { vi: 'Trung tâm đào tạo', ko: '교육 센터' },
  'Our centers': { vi: 'Trung tâm của chúng tôi', ko: '우리 센터' },
  'Find a KBIT center': { vi: 'Tìm trung tâm KBIT', ko: 'KBIT 센터 찾기' },
  'Visit or inquire about our centers': {
    vi: 'Ghé thăm hoặc tìm hiểu về các trung tâm của chúng tôi',
    ko: '센터를 방문하거나 문의해 보세요',
  },
  'Reach us directly to get directions, schedule a visit, or learn more about what each KBIT center offers.': {
    vi: 'Liên hệ trực tiếp với chúng tôi để được chỉ đường, đặt lịch ghé thăm hoặc tìm hiểu thêm về những gì mỗi trung tâm KBIT mang lại.',
    ko: '길 안내를 받거나 방문을 예약하고, 각 KBIT 센터가 제공하는 내용을 자세히 알아보려면 직접 문의해 주세요.',
  },
  'Contact us': { vi: 'Liên hệ với chúng tôi', ko: '문의하기' },

  // ── About ──
  'ABOUT': { vi: 'GIỚI THIỆU', ko: '소개' },
  'Network / Standards / Exchange': { vi: 'Mạng lưới / Tiêu chuẩn / Giao lưu', ko: '네트워크 / 표준 / 교류' },
  'Education centers': { vi: 'Trung tâm đào tạo', ko: '교육 센터' },
  'Expert doctors': { vi: 'Bác sĩ chuyên gia', ko: '전문 의료진' },
  'Countries reached': { vi: 'Quốc gia kết nối', ko: '연결 국가' },
  'Members connected': { vi: 'Hội viên kết nối', ko: '연결 회원' },
  "Bring Korea's newest rejuvenation technology and training standards within reach of every member clinic — so your patients always benefit from proven, current techniques.": {
    vi: 'Đưa công nghệ trẻ hóa mới nhất và chuẩn đào tạo của Hàn Quốc đến gần hơn với từng phòng khám hội viên — để bệnh nhân luôn được hưởng lợi từ những kỹ thuật đã được chứng minh và cập nhật.',
    ko: '한국의 최신 재생 기술과 교육 표준을 모든 회원 클리닉이 활용할 수 있도록 연결하여, 환자들이 검증된 최신 기법의 혜택을 받을 수 있게 합니다.',
  },
  'One trusted bridge between Korean clinical innovation and aesthetic practitioners across Vietnam, Asia, and beyond.': {
    vi: 'Một cầu nối đáng tin cậy giữa đổi mới lâm sàng Hàn Quốc và đội ngũ hành nghề thẩm mỹ tại Việt Nam, châu Á và xa hơn nữa.',
    ko: '한국 임상 혁신과 베트남, 아시아 및 그 너머의 미용 의료 전문가를 잇는 신뢰할 수 있는 가교입니다.',
  },
  'From symposiums in Seoul to MOU signings in Ho Chi Minh City, KBIT grew out of working partnerships between hospitals, clinics, and educators on both sides.': {
    vi: 'Từ các hội nghị chuyên đề tại Seoul đến lễ ký MOU ở TP.HCM, KBIT phát triển từ những hợp tác thực chất giữa bệnh viện, phòng khám và đơn vị đào tạo của hai bên.',
    ko: '서울의 심포지엄부터 호치민시의 MOU 체결까지, KBIT는 양국의 병원, 클리닉, 교육기관 간 실질적 협력에서 성장했습니다.',
  },
  'Latest techniques': { vi: 'Kỹ thuật mới nhất', ko: '최신 기법' },
  'Direct from Seoul': { vi: 'Trực tiếp từ Seoul', ko: '서울에서 직접' },
  'Cross-border': { vi: 'Xuyên biên giới', ko: '국경을 넘는 협력' },
  'Korea · Vietnam · Asia': { vi: 'Hàn Quốc · Việt Nam · Châu Á', ko: '한국 · 베트남 · 아시아' },
  'Member network': { vi: 'Mạng lưới hội viên', ko: '회원 네트워크' },
  'Clinics + doctors': { vi: 'Phòng khám + bác sĩ', ko: '클리닉 + 의료진' },
  'Mission': { vi: 'Sứ mệnh', ko: '미션' },
  'Vision': { vi: 'Tầm nhìn', ko: '비전' },
  'Advancing your practice': { vi: 'Nâng tầm hoạt động chuyên môn', ko: '진료 역량 향상' },
  'A bridge between two worlds': { vi: 'Cầu nối giữa hai hệ sinh thái', ko: '두 세계를 잇는 다리' },
  'Our story': { vi: 'Câu chuyện của chúng tôi', ko: '우리의 이야기' },
  'Born from real exchange': { vi: 'Hình thành từ giao lưu thực chất', ko: '실질적 교류에서 시작' },
  'Training programs': { vi: 'Chương trình đào tạo', ko: '교육 프로그램' },
  'Clinical standards': { vi: 'Tiêu chuẩn lâm sàng', ko: '임상 표준' },
  'Certification': { vi: 'Chứng nhận', ko: '인증' },
  'Korea': { vi: 'Hàn Quốc', ko: '한국' },
  'Vietnam': { vi: 'Việt Nam', ko: '베트남' },
  'Asia': { vi: 'Châu Á', ko: '아시아' },
  'Symposiums': { vi: 'Hội nghị chuyên đề', ko: '심포지엄' },
  'Partnerships': { vi: 'Quan hệ đối tác', ko: '파트너십' },
  'Who we are': { vi: 'Chúng tôi là ai', ko: '우리는 누구인가' },
  'Korean aesthetic medicine, shared across borders': { vi: 'Y học thẩm mỹ Hàn Quốc, lan tỏa qua biên giới', ko: '국경을 넘어 공유되는 한국 미용의학' },
  "KBIT brings Korea's leading aesthetic doctors, training centers, and clinics together with practitioners across Vietnam and Asia.": {
    vi: 'KBIT kết nối các bác sĩ thẩm mỹ, trung tâm đào tạo và phòng khám hàng đầu Hàn Quốc với đội ngũ hành nghề tại Việt Nam và châu Á.',
    ko: 'KBIT는 한국의 선도적인 미용 의료진, 교육 센터, 클리닉을 베트남과 아시아의 전문가들과 연결합니다.',
  },
  'KAT 2025 — Korea · Vietnam clinical exchange': { vi: 'KAT 2025 — Giao lưu lâm sàng Hàn Quốc · Việt Nam', ko: 'KAT 2025 — 한국 · 베트남 임상 교류' },
  'Contact team': { vi: 'Liên hệ đội ngũ', ko: '팀에 문의하기' },
  'Programs': { vi: 'Chương trình', ko: '프로그램' },
  'Our network': { vi: 'Mạng lưới của chúng tôi', ko: '우리 네트워크' },
  'Network scale': { vi: 'Quy mô mạng lưới', ko: '네트워크 규모' },
  'Education, events, and exchange — one connected community.': { vi: 'Đào tạo, sự kiện và giao lưu — một cộng đồng được kết nối.', ko: '교육, 행사, 교류 — 하나로 연결된 커뮤니티.' },
  'Mission / Vision / History': { vi: 'Sứ mệnh / Tầm nhìn / Lịch sử', ko: '미션 / 비전 / 역사' },
  'What we stand for': { vi: 'Điều chúng tôi theo đuổi', ko: '우리가 지향하는 가치' },
  'Network in motion': { vi: 'Mạng lưới đang chuyển động', ko: '움직이는 네트워크' },
  'Moments from the field': { vi: 'Khoảnh khắc từ thực địa', ko: '현장의 순간들' },
  'MOU signing — Le Van Thinh Hospital × KBIT, 2024': { vi: 'Ký kết MOU — Bệnh viện Lê Văn Thịnh × KBIT, 2024', ko: 'MOU 체결 — 레반틴 병원 × KBIT, 2024' },
  'Specialist seminar — KAT 2025': { vi: 'Hội thảo chuyên gia — KAT 2025', ko: '전문가 세미나 — KAT 2025' },
  'KAT 2025 — conference session': { vi: 'KAT 2025 — phiên hội nghị', ko: 'KAT 2025 — 컨퍼런스 세션' },
  'Leadership': { vi: 'Lãnh đạo', ko: '리더십' },
  'The people and places behind KBIT': { vi: 'Con người và địa điểm phía sau KBIT', ko: 'KBIT를 만드는 사람과 공간' },
  'Lead executive': { vi: 'Lãnh đạo điều hành', ko: '총괄 리더' },
  'Network liaison': { vi: 'Kết nối mạng lưới', ko: '네트워크 연락 담당' },
  'Korea / Vietnam / Asia': { vi: 'Hàn Quốc / Việt Nam / Châu Á', ko: '한국 / 베트남 / 아시아' },
  'Network anchor': { vi: 'Điểm neo mạng lưới', ko: '네트워크 거점' },

  // ── Contact ──
  'CONTACT': { vi: 'LIÊN HỆ', ko: '문의' },
  'Support / Offices / Inquiry': { vi: 'Hỗ trợ / Văn phòng / Yêu cầu', ko: '지원 / 사무소 / 문의' },
  'Quick support channels': { vi: 'Kênh hỗ trợ nhanh', ko: '빠른 지원 채널' },
  'Reach the right team': { vi: 'Kết nối đúng đội ngũ', ko: '알맞은 팀에 연결' },
  'We are always ready to listen and support you.': { vi: 'Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn.', ko: '저희는 언제나 경청하고 지원할 준비가 되어 있습니다.' },
  'Use the contact form, email, or the office details below to reach the team most relevant to your need.': { vi: 'Sử dụng biểu mẫu liên hệ, email hoặc thông tin văn phòng bên dưới để kết nối với đội ngũ phù hợp nhất với nhu cầu của bạn.', ko: '문의 양식, 이메일 또는 아래 사무소 정보를 통해 필요한 업무에 가장 적합한 팀과 연결하세요.' },
  'Send inquiry': { vi: 'Gửi yêu cầu', ko: '문의 보내기' },
  'Call Vietnam office': { vi: 'Gọi văn phòng Việt Nam', ko: '베트남 사무소 전화' },
  'Inquiry form': { vi: 'Biểu mẫu yêu cầu', ko: '문의 양식' },
  'Send a message': { vi: 'Gửi tin nhắn', ko: '메시지 보내기' },
  'Name': { vi: 'Họ tên', ko: '이름' },
  'Your full name': { vi: 'Họ tên đầy đủ', ko: '성명' },
  'Email': { vi: 'Email', ko: '이메일' },
  'Phone': { vi: 'Điện thoại', ko: '전화' },
  'Phone number': { vi: 'Số điện thoại', ko: '전화번호' },
  'Subject': { vi: 'Chủ đề', ko: '제목' },
  'Select a subject': { vi: 'Chọn chủ đề', ko: '제목 선택' },
  'Message': { vi: 'Nội dung', ko: '메시지' },
  'Tell us what you need help with...': { vi: 'Cho chúng tôi biết bạn cần hỗ trợ gì...', ko: '어떤 도움이 필요한지 알려주세요...' },
  'Submit inquiry': { vi: 'Gửi yêu cầu', ko: '문의 제출' },
  'This UI is ready for backend wiring.': { vi: 'Giao diện này đã sẵn sàng để kết nối backend.', ko: '이 UI는 백엔드 연동 준비가 되어 있습니다.' },
  'Response flow': { vi: 'Quy trình phản hồi', ko: '응답 절차' },
  'What happens after you send it': { vi: 'Điều gì xảy ra sau khi gửi', ko: '제출 후 진행 과정' },
  'Inquiry received by the KBIT coordination team.': { vi: 'Tiếp nhận: Đội ngũ điều phối của KBIT sẽ tiếp nhận yêu cầu từ bạn.', ko: 'KBIT 코디네이션 팀이 문의를 접수합니다.' },
  'Membership, event, or partnership request is routed to the right office.': { vi: 'Chuyển xử lý: Các yêu cầu về hội viên, sự kiện hoặc hợp tác sẽ được chuyển đến văn phòng phụ trách phù hợp.', ko: '회원, 행사 또는 파트너십 문의가 담당 사무소로 전달됩니다.' },
  'A coordinator follows up with the next action or required documents.': { vi: 'Phản hồi: Điều phối viên sẽ liên hệ lại với bạn để hướng dẫn các bước tiếp theo hoặc các tài liệu cần chuẩn bị.', ko: '담당자가 다음 단계 또는 필요한 서류를 안내합니다.' },
  'Direct contact': { vi: 'Liên hệ trực tiếp', ko: '직접 연락' },
  'Working hours': { vi: 'Giờ làm việc', ko: '운영 시간' },
  'Korea + Vietnam office coverage': { vi: 'Phạm vi hỗ trợ văn phòng Hàn Quốc + Việt Nam', ko: '한국 + 베트남 사무소 지원' },
  'Reach us in person': { vi: 'Gặp trực tiếp chúng tôi', ko: '직접 방문 문의' },
  'Hours': { vi: 'Giờ làm việc', ko: '시간' },
  'Contact person': { vi: 'Người phụ trách', ko: '담당자' },

  // ── Membership ──
  'MEMBER': { vi: 'HỘI VIÊN', ko: '회원' },
  'Professional Excellence Program': { vi: 'Chương trình phát triển chuyên môn', ko: '전문성 향상 프로그램' },
  'Membership sections': { vi: 'Các mục hội viên', ko: '회원 섹션' },
  'Structure': { vi: 'Cơ cấu', ko: '구성' },
  'Benefits': { vi: 'Quyền lợi', ko: '혜택' },
  'Requirements': { vi: 'Yêu cầu', ko: '요건' },
  'Fee': { vi: 'Phí', ko: '회비' },
  'Forms': { vi: 'Biểu mẫu', ko: '양식' },
  'How to register': { vi: 'Cách đăng ký', ko: '등록 방법' },
  'Contact page': { vi: 'Trang liên hệ', ko: '문의 페이지' },
  'General Inquiry': { vi: 'Yêu cầu chung', ko: '일반 문의' },
  'Event Registration': { vi: 'Đăng ký sự kiện', ko: '행사 등록' },
  'Collaboration': { vi: 'Hợp tác', ko: '협업' },
  'Other': { vi: 'Khác', ko: '기타' },
  'Use contact form': { vi: 'Sử dụng biểu mẫu liên hệ', ko: '문의 양식 사용' },

  // ── Supabase Membership Platform ──
  'Apply online': { vi: 'Đăng ký trực tuyến', ko: '온라인 신청' },
  'Member portal': { vi: 'Cổng hội viên', ko: '회원 포털' },
  'Member login': { vi: 'Đăng nhập hội viên', ko: '회원 로그인' },
  'Sign in to view your membership status and member documents.': { vi: 'Đăng nhập để xem trạng thái hội viên và tài liệu dành cho hội viên.', ko: '회원 상태와 회원 문서를 확인하려면 로그인하세요.' },
  'Member login is not configured yet.': { vi: 'Đăng nhập hội viên chưa được cấu hình.', ko: '회원 로그인이 아직 설정되지 않았습니다.' },
  'Password': { vi: 'Mật khẩu', ko: '비밀번호' },
  'Magic link': { vi: 'Liên kết đăng nhập', ko: '매직 링크' },
  'Check your email for the login link.': { vi: 'Vui lòng kiểm tra email để nhận liên kết đăng nhập.', ko: '로그인 링크를 이메일에서 확인하세요.' },
  'Unable to sign in.': { vi: 'Không thể đăng nhập.', ko: '로그인할 수 없습니다.' },
  'Sign in': { vi: 'Đăng nhập', ko: '로그인' },
  'Apply for membership': { vi: 'Đăng ký hội viên', ko: '회원 신청' },
  'My account': { vi: 'Tài khoản của tôi', ko: '내 계정' },
  'Sign out': { vi: 'Đăng xuất', ko: '로그아웃' },
  'Member portal is not configured yet.': { vi: 'Cổng hội viên chưa được cấu hình.', ko: '회원 포털이 아직 설정되지 않았습니다.' },
  'Unable to load member account.': { vi: 'Không thể tải tài khoản hội viên.', ko: '회원 계정을 불러올 수 없습니다.' },
  'Unable to open document.': { vi: 'Không thể mở tài liệu.', ko: '문서를 열 수 없습니다.' },
  'No active membership found': { vi: 'Chưa tìm thấy hội viên đang hoạt động', ko: '활성 회원 정보가 없습니다' },
  'If you already applied, KBIT staff will contact you after payment confirmation and account creation.': { vi: 'Nếu bạn đã đăng ký, nhân viên KBIT sẽ liên hệ sau khi xác nhận thanh toán và tạo tài khoản hội viên.', ko: '이미 신청하셨다면 결제 확인 및 회원 계정 생성 후 KBIT 직원이 연락드립니다.' },
  'Membership status': { vi: 'Trạng thái hội viên', ko: '회원 상태' },
  'Tier': { vi: 'Hạng hội viên', ko: '등급' },
  'Plan': { vi: 'Gói hội viên', ko: '플랜' },
  'Status': { vi: 'Trạng thái', ko: '상태' },
  'Expiry': { vi: 'Ngày hết hạn', ko: '만료일' },
  'Lifetime': { vi: 'Trọn đời', ko: '평생' },
  'Member documents': { vi: 'Tài liệu hội viên', ko: '회원 문서' },
  'No documents are available for your membership yet.': { vi: 'Chưa có tài liệu nào dành cho hạng hội viên của bạn.', ko: '현재 회원 등급에서 이용 가능한 문서가 없습니다.' },
  'Online membership application': { vi: 'Đăng ký hội viên trực tuyến', ko: '온라인 회원 신청' },
  'Apply for KBIT membership': { vi: 'Đăng ký hội viên KBIT', ko: 'KBIT 회원 신청' },
  'Submit your application online. KBIT staff will contact you to confirm payment and create your member account.': { vi: 'Gửi hồ sơ trực tuyến. Nhân viên KBIT sẽ liên hệ để xác nhận thanh toán và tạo tài khoản hội viên.', ko: '온라인으로 신청서를 제출하세요. KBIT 직원이 결제 확인 및 회원 계정 생성을 위해 연락드립니다.' },
  'Online application is not configured yet.': { vi: 'Đăng ký trực tuyến chưa được cấu hình.', ko: '온라인 신청이 아직 설정되지 않았습니다.' },
  'Unable to load membership plans.': { vi: 'Không thể tải gói hội viên.', ko: '회원 플랜을 불러올 수 없습니다.' },
  'Please select a membership plan.': { vi: 'Vui lòng chọn gói hội viên.', ko: '회원 플랜을 선택하세요.' },
  'Application submitted successfully.': { vi: 'Đã gửi hồ sơ đăng ký thành công.', ko: '신청서가 성공적으로 제출되었습니다.' },
  'Unable to submit application.': { vi: 'Không thể gửi hồ sơ đăng ký.', ko: '신청서를 제출할 수 없습니다.' },
  'Select plan': { vi: 'Chọn gói', ko: '플랜 선택' },
  'months': { vi: 'tháng', ko: '개월' },
  'Applicant information': { vi: 'Thông tin người đăng ký', ko: '신청자 정보' },
  'Full name': { vi: 'Họ và tên', ko: '성명' },
  'City / Country': { vi: 'Thành phố / Quốc gia', ko: '도시 / 국가' },
  'Clinic / organization': { vi: 'Phòng khám / tổ chức', ko: '클리닉 / 기관' },
  'Specialty / role': { vi: 'Chuyên môn / vai trò', ko: '전문 분야 / 역할' },
  'Reason for joining': { vi: 'Lý do tham gia', ko: '가입 사유' },
  'Submitting...': { vi: 'Đang gửi...', ko: '제출 중...' },
  'Submit application': { vi: 'Gửi hồ sơ đăng ký', ko: '신청서 제출' },
  'Loading...': { vi: 'Đang tải...', ko: '로딩 중...' },
  'Download': { vi: 'Tải xuống', ko: '다운로드' },
}

export function tr(en: string, locale: Locale): string {
  if (locale === 'en') return en
  const entry = UI[en]
  return entry ? entry[locale] || en : en
}
